const DIR = {
  N: 0,
  E: 1,
  S: 2,
  W: 3,
};

const INPUT_TO_DIR = {
  N: DIR.N,
  NORTH: DIR.N,
  E: DIR.E,
  EAST: DIR.E,
  S: DIR.S,
  SOUTH: DIR.S,
  W: DIR.W,
  WEST: DIR.W,
};

const MAX_LOCATION_ITEMS = 3;
const START_POS = { x: 7, y: 4 };

const ALL_ITEMS = [
  { id: 10, name: "a KEY", flag: 1 },
  { id: 11, name: "an AXE", flag: 1 },
  { id: 12, name: "STICKS", flag: 1 },
  { id: 13, name: "sheeplegs", flag: 0 },
  { id: 14, name: "MUSHROOMS", flag: 1 },
  { id: 15, name: "MONEY", flag: 1 },
  { id: 16, name: "a BARREL", flag: 1 },
  { id: 17, name: "a sheeptrunk", flag: 0 },
  { id: 18, name: "BERRIES", flag: 1 },
  { id: 19, name: "WOOL", flag: 1 },
  { id: 20, name: "a sheepskin", flag: 0 },
  { id: 21, name: "a BAG", flag: 1 },
  { id: 22, name: "a RAG", flag: 1 },
  { id: 23, name: "a sheephead", flag: 0 },
  { id: 24, name: "a SPADE", flag: 1 },
  { id: 25, name: "SULPHUR", flag: 1 },
  { id: 26, name: "a solid poison", flag: 0 },
  { id: 27, name: "a BUCKET", flag: 1 },
  { id: 28, name: "TAR", flag: 1 },
  { id: 29, name: "a liquid poison", flag: 0 },
  { id: 30, name: "a dead dragon", flag: 0 },
  { id: 31, name: "a STONE", flag: 1 },
  { id: 32, name: "a FISH", flag: 1 },
  { id: 33, name: "a KNIFE", flag: 1 },
  { id: 34, name: "a DRAGONSKIN", flag: 1 },
  { id: 35, name: "dragonskin SHOES", flag: 1 },
  { id: 36, name: "a PRIZE", flag: 1 },
  { id: 37, name: "a SHEEP", flag: 1 },
];

const ITEM_STARTING_LOCATIONS = {
  "3-1": 31,
  "5-1": 27,
  "7-1": 14,
  "3-2": 10,
  "7-2": 18,
  "2-3": 32,
  "4-4": 21,
  "5-5": 33,
  "4-6": 24,
};

const MILESTONES_TO_ASSEMBLE = 6;

const ITEMS = [
  {
    itemId: 10,
    locationKey: "6-5",
    result: 11,
    onLocation: false,
    message: "You opened a tool shed and took an axe",
    milestone: false,
  },
  {
    itemId: 11,
    locationKey: "7-6",
    result: 12,
    onLocation: false,
    message: "You cut sticks for sheeplegs",
    milestone: false,
  },
  {
    itemId: 12,
    locationKey: "3-4",
    result: 13,
    onLocation: true,
    message: "You prepared legs for your fake sheep",
    milestone: true,
  },
  {
    itemId: 14,
    locationKey: "4-3",
    result: 15,
    onLocation: false,
    message: "The tavern owner paid you money",
    milestone: false,
  },
  {
    itemId: 15,
    locationKey: "7-3",
    result: 16,
    onLocation: false,
    message: "The cooper sold you a new barrel",
    milestone: false,
  },
  {
    itemId: 16,
    locationKey: "3-4",
    result: 17,
    onLocation: true,
    message: "You made a nice sheeptrunk",
    milestone: true,
  },
  {
    itemId: 18,
    locationKey: "6-3",
    result: 19,
    onLocation: false,
    message: "The butcher gave you wool",
    milestone: false,
  },
  {
    itemId: 19,
    locationKey: "3-4",
    result: 20,
    onLocation: true,
    message: "You prepared skin for your fake sheep",
    milestone: true,
  },
  {
    itemId: 21,
    locationKey: "7-5",
    result: 22,
    onLocation: false,
    message: "You used your tools to make a rag",
    milestone: false,
  },
  {
    itemId: 22,
    locationKey: "3-4",
    result: 23,
    onLocation: true,
    message: "You made a fake sheephead",
    milestone: true,
  },
  {
    itemId: 24,
    locationKey: "1-1",
    result: 25,
    onLocation: false,
    message: "You are digging... That's enough sulphur!",
    milestone: false,
  },
  {
    itemId: 25,
    locationKey: "3-4",
    result: 26,
    onLocation: true,
    message: "You prepared a solid poison",
    milestone: true,
  },
  {
    itemId: 27,
    locationKey: "1-2",
    result: 28,
    onLocation: false,
    message: "You got a bucket full of tar",
    milestone: false,
  },
  {
    itemId: 28,
    locationKey: "3-4",
    result: 29,
    onLocation: true,
    message: "You prepared a liquid poison",
    milestone: true,
  },
  {
    itemId: 37,
    locationKey: "3-4",
    result: 30,
    onLocation: true,
    message: "The dragon ate your sheep and died!",
    milestone: false,
  },
  {
    itemId: 33,
    locationKey: "3-4",
    result: 34,
    onLocation: false,
    message: "You cut a piece of dragon's skin",
    milestone: false,
  },
  {
    itemId: 34,
    locationKey: "7-5",
    result: 35,
    onLocation: false,
    message: "You used your tools to make shoes",
    milestone: false,
  },
  {
    itemId: 35,
    locationKey: "1-4",
    result: 36,
    onLocation: false,
    message: "The King is impressed by your shoes",
    milestone: false,
  },
];

const MESSAGES = {
  GOING: {
    [DIR.N]: "You are goiong north...",
    [DIR.E]: "You are goiong east...",
    [DIR.S]: "You are goiong south...",
    [DIR.W]: "You are goiong west...",
  },
  TAKE_SUCCESS: (name) => `You are taking ${name}`,
  CANT_CARRY: "You can't carry it",
  NOT_HERE: "There isn't anything like that here",
  ALREADY_CARRY: (name) => `You are carrying ${name}`,
  CARRY_NOTHING: "You are carrying nothing",
  DROP_SUCCESS: (name) => `You are about to drop ${name}`,
  DROP_EMPTY: "You are not carrying anything",
  DROP_FULL: "You can't store any more here",
  DROP_NOT_HAVE: (name) => `You are not carrying ${name}`,
  USE_NOT_HAVE: "You aren't carrying anything like that",
  USE_NOTHING: "Nothing happened",
  WIN: "You won! The King rewards you!",
};

const VOCABULARY_SCREEN = [
  "North or N, South or S",
  "East or E, West or W",
  "Take (object) or T (object)",
  "Drop (object) or D (object)",
  "Use (object) or U (object)",
  "GOSSIPS or G, Vocabulary or V",
  "Press any key",
];

const GOSSIPS_SCREEN = [
  "The woodcutter lost his home key...",
  "The butcher likes fruit... The cooper is greedy...",
  "Dratewka plans to make a poisoned bait for the dragon...",
  "The tavern owner is buying food from the pickers...",
  "Making a rag from a bag...",
  "Press any key",
];
export {
  DIR,
  INPUT_TO_DIR,
  MAX_LOCATION_ITEMS,
  START_POS,
  MESSAGES,
  VOCABULARY_SCREEN,
  GOSSIPS_SCREEN,
  ITEMS,
  ALL_ITEMS,
  ITEM_STARTING_LOCATIONS,
  MILESTONES_TO_ASSEMBLE,
};
